Description of Udag
Udag
PURPOSE
Ud = Udag(U,L,Neigh,Ext_Ind)
SYNOPSIS
function Ud = Udag(U,Comm)
DESCRIPTION
 Ud = Udag(U,L,Neigh,Ext_Ind)
 Compute U^dag in order to optimize a version of the fermion matrix.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MolecularDynamics U = MoleculerDynamics(U,@Mh,beta,ge,Nc,dt,N_MD,Comm)
MolecularDynamicsRPhi U = MoleculerDynamicsRPhi(U,@Mh,beta,ge,Nc,Nf,Nadj,dt,N_MD,algo,Comm)
main_update define GL's, gauge-group, gauge-rep, chem-pot. gauge coupling, mass(es)
SOURCE CODE
function Ud = Udag(U,Comm)
% Ud = Udag(U,L,Neigh,Ext_Ind)
% Compute U^dag in order to optimize a version of the fermion matrix.
UP=1;
L=Comm.l;
D=length(L); V=prod(L);
for mu=1:D
 n_up = Comm.neigh(Comm.extind,mu,UP);
 Ud(:,:,mu,Comm.extind) = U(:,:,mu,n_up);
end
Ud = conj(permute(Ud,[2 1 3 4]));